# Generated by Django 4.1.5 on 2023-01-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitob',
            old_name='sahofa',
            new_name='sahifa',
        ),
    ]
