# Generated by Django 4.1.5 on 2023-01-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_rename_sahofa_kitob_sahifa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talaba',
            old_name='bitriruvchi',
            new_name='bitruvchi',
        ),
    ]
