# Generated by Django 4.1.5 on 2023-01-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_alter_record_qaytargan_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='ish_vaqti',
            field=models.CharField(choices=[('7:00-12:00', '7:00-12:00'), ('13:00-18:00', '13:00-18:00')], max_length=30),
        ),
    ]
